exports.FLOW_BANKACC = {  
    accno_2991 : {
        accountNumber: "0633022991",
        accountName: "กระแสกรุงเทพ",
        accountType: 3,
        bankName: "BangkokBank",
        bankCode: "002",
        bankAccountId: 42505,
        bankId: 1,
        branch: "เอกมัย",
        isDefault: false,
        chartOfAccountId: 51475478,
        bankUrl: "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    accno_riceInAdv : {
        accountNumber: "11111",
        accountName: "ซื้อข้าวล่วงหน้า",
        accountType: 1,
        bankName: "ThaiCreditRetailBank",
        bankCode: "071",
        bankAccountId: 45173,
        bankId: 31,
        branch: "",
        isDefault: false,
        chartOfAccountId: 56266417,
        bankUrl: "https://media.flowaccount.com/share/logo-bank/thaicredit.png"
    },
    accno_2309: {
        accountNumber: "0483402309",
        accountName: "กสิกร จามฯ",
        accountType: 1,
        bankName: "KasikornBank",
        bankCode: "004",
        bankAccountId: 42507,
        bankId: 2,
        branch: "จามจุรีสแควร์",
        isDefault: false,
        chartOfAccountId: 51476350,
        bankUrl: "https://media.flowaccount.com/share/logo-bank/k-bank.png"
    },
    accno_9919: {
        accountNumber: "0630339919",
        accountName: "กรุงเทพเอกมัย",
        accountType: 1,
        bankName: "BangkokBank",
        bankCode: "002",
        bankAccountId: 42504,
        bankId: 1,
        branch: "เอกมัย",
        isDefault: false,
        chartOfAccountId: 51475042,
        bankUrl: "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    accno_6347 : {
        accountNumber: "0628106347",
        accountName: "กสิกร ชุมพร",
        accountType: 1,
        bankName: "KasikornBank",
        bankCode: "004",
        bankAccountId: 42503,
        bankId: 2,
        branch: "ชุมพร",
        isDefault: false,
        chartOfAccountId: 51475041,
        bankUrl: "https://media.flowaccount.com/share/logo-bank/k-bank.png"
    },
}