exports.FLOW_BANKACC = [   
    {
        "accountNumber": "0633022991",
        "accountName": "กระแสกรุงเทพ",
        "accountType": 3,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 42505,
        "bankId": 1,
        "branch": "เอกมัย",
        "isDefault": false,
        "chartOfAccountId": 51475478,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1090000002",
        "accountName": "เงินโอนรับ FoodStory ร้านยักษ์กะโจน ท่าแพ",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49953,
        "bankId": 1,
        "branch": "FoodStory ร้านยักษ์กะโจน ท่าแพ",
        "isDefault": false,
        "chartOfAccountId": 63199447,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1090000001",
        "accountName": "เงินสดรับ FoodStory ร้านยักษ์กะโจน ท่าแพ",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49952,
        "bankId": 1,
        "branch": "FoodStory ร้านยักษ์กะโจน ท่าแพ",
        "isDefault": false,
        "chartOfAccountId": 63199446,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1080000002",
        "accountName": "เงินโอนรับ FoodStory ชุมพรคาบาน่า",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49951,
        "bankId": 1,
        "branch": "FoodStory ชุมพรคาบาน่า",
        "isDefault": false,
        "chartOfAccountId": 63199010,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1080000001",
        "accountName": "เงินสดรับ FoodStory ชุมพรคาบาน่า",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49949,
        "bankId": 1,
        "branch": "FoodStory ชุมพรคาบาน่า",
        "isDefault": false,
        "chartOfAccountId": 63199008,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1060000002",
        "accountName": "เงินโอนรับ รถธรรมธุรกิจ",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49948,
        "bankId": 1,
        "branch": "รถธรรมธุรกิจ",
        "isDefault": false,
        "chartOfAccountId": 63199007,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1060000001",
        "accountName": "เงินสดรับ รถธรรมธุรกิจ",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49947,
        "bankId": 1,
        "branch": "รถธรรมธุรกิจ",
        "isDefault": false,
        "chartOfAccountId": 63199006,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1070000002",
        "accountName": "เงินโอนรับ รถร่วมธรรมธุรกิจ 1",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49946,
        "bankId": 1,
        "branch": "รถร่วมธรรมธุรกิจ 1",
        "isDefault": false,
        "chartOfAccountId": 63198570,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1070000001",
        "accountName": "เงินสดรับ รถร่วมธรรมธุรกิจ 1",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49945,
        "bankId": 1,
        "branch": "รถร่วมธรรมธุรกิจ 1",
        "isDefault": false,
        "chartOfAccountId": 63198569,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1050000002",
        "accountName": "เงินโอนรับ Ocha ครัวชุมพรคาบาน่า",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49942,
        "bankId": 1,
        "branch": "Ocha ครัวชุมพรคาบาน่า",
        "isDefault": false,
        "chartOfAccountId": 63198566,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1050000001",
        "accountName": "เงินสดรับ Ocha ครัวชุมพรคาบาน่า",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49941,
        "bankId": 1,
        "branch": "Ocha ครัวชุมพรคาบาน่า",
        "isDefault": false,
        "chartOfAccountId": 63198130,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1040000002",
        "accountName": "เงินโอนรับ Ocha Front ชุมพรคาบาน่า",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49940,
        "bankId": 1,
        "branch": "Ocha Front ชุมพรคาบาน่า",
        "isDefault": false,
        "chartOfAccountId": 63197694,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1040000001",
        "accountName": "เงินสดรับ Ocha Front ชุมพรคาบาน่า",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49939,
        "bankId": 1,
        "branch": "Ocha Front ชุมพรคาบาน่า",
        "isDefault": false,
        "chartOfAccountId": 63197693,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1030000002",
        "accountName": "เงินโอนรับ Ocha ฐานธรรมฯสันป่าตอง(ร้านยักษ์กะโจน)",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49938,
        "bankId": 1,
        "branch": "Ocha ฐานธรรมฯสันป่าตอง(ร้านยักษ์กะโจน)",
        "isDefault": false,
        "chartOfAccountId": 63197692,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1030000001",
        "accountName": "เงินสดรับ Ocha ฐานธรรมฯสันป่าตอง(ร้านยักษ์กะโจน)",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49936,
        "bankId": 1,
        "branch": "Ocha ฐานธรรมฯสันป่าตอง(ร้านยักษ์กะโจน)",
        "isDefault": false,
        "chartOfAccountId": 63197690,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1010000002",
        "accountName": "เงินโอนรับ Ocha ผักพระราม๙",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49934,
        "bankId": 1,
        "branch": "Ocha ผักพระราม๙",
        "isDefault": false,
        "chartOfAccountId": 63197688,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "101000000-1",
        "accountName": "เงินสดรับ Ocha ผักพระราม๙",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49933,
        "bankId": 1,
        "branch": "Ocha ผักพระราม๙",
        "isDefault": false,
        "chartOfAccountId": 63197687,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1000000002",
        "accountName": "เงินโอนรับ Ocha ข้าวแปรรูป พระราม๙",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49932,
        "bankId": 1,
        "branch": "Ocha ข้าวแปรรูป พระราม๙",
        "isDefault": false,
        "chartOfAccountId": 63197686,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "1000000001",
        "accountName": "เงินสดรับ Ocha ข้าวแปรรูป พระราม๙",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 49931,
        "bankId": 1,
        "branch": "Ocha ข้าวแปรรูป พระราม๙",
        "isDefault": false,
        "chartOfAccountId": 63197685,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "11111",
        "accountName": "ซื้อข้าวล่วงหน้า",
        "accountType": 1,
        "bankName": "ThaiCreditRetailBank",
        "bankCode": "071",
        "bankAccountId": 45173,
        "bankId": 31,
        "branch": "",
        "isDefault": false,
        "chartOfAccountId": 56266417,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/thaicredit.png"
    },
    {
        "accountNumber": "003",
        "accountName": "เงินสดห้องพัก",
        "accountType": 1,
        "bankName": "ThaiCreditRetailBank",
        "bankCode": "071",
        "bankAccountId": 43970,
        "bankId": 31,
        "branch": "",
        "isDefault": false,
        "chartOfAccountId": 54308627,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/thaicredit.png"
    },
    {
        "accountNumber": "002",
        "accountName": "เงินสดยักษ์กะโจน@ชุมพร คาบาน่า",
        "accountType": 1,
        "bankName": "ThaiCreditRetailBank",
        "bankCode": "071",
        "bankAccountId": 43969,
        "bankId": 31,
        "branch": "",
        "isDefault": false,
        "chartOfAccountId": 54308190,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/thaicredit.png"
    },
    {
        "accountNumber": "001",
        "accountName": "เงินสดซื้อปลา",
        "accountType": 1,
        "bankName": "ThaiCreditRetailBank",
        "bankCode": "071",
        "bankAccountId": 43967,
        "bankId": 31,
        "branch": "ชุมพรคาบาน่า",
        "isDefault": false,
        "chartOfAccountId": 54305135,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/thaicredit.png"
    },
    {
        "accountNumber": "0483402309",
        "accountName": "กสิกร จามฯ",
        "accountType": 1,
        "bankName": "KasikornBank",
        "bankCode": "004",
        "bankAccountId": 42507,
        "bankId": 2,
        "branch": "จามจุรีสแควร์",
        "isDefault": false,
        "chartOfAccountId": 51476350,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/k-bank.png"
    },
    {
        "accountNumber": "0630339919",
        "accountName": "กรุงเทพเอกมัย",
        "accountType": 1,
        "bankName": "BangkokBank",
        "bankCode": "002",
        "bankAccountId": 42504,
        "bankId": 1,
        "branch": "เอกมัย",
        "isDefault": false,
        "chartOfAccountId": 51475042,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/bangkokBank.png"
    },
    {
        "accountNumber": "0628106347",
        "accountName": "กสิกร ชุมพร",
        "accountType": 1,
        "bankName": "KasikornBank",
        "bankCode": "004",
        "bankAccountId": 42503,
        "bankId": 2,
        "branch": "ชุมพร",
        "isDefault": false,
        "chartOfAccountId": 51475041,
        "bankUrl": "https://media.flowaccount.com/share/logo-bank/k-bank.png"
    }
]